

/*
drop table roles if exists;
drop table users if exists;
create table roles (role_id bigint generated by default as identity, authority varchar(255), userid bigint not null, primary key (role_id));
create table users (userid bigint generated by default as identity, password varchar(255), username varchar(255), primary key (userid));
alter table roles add constraint FKb3b5sm6dr1lvgl2xjtvnavnyb foreign key (userid) references users;
*/