server:
    port: 8080
    context-path: /ui


security:
    basic:
        enabled: false
        
    oauth2:
        client:
            client-id: oauth_client_app
            client-secret: oauth_client_secret
            access-token-uri: http://localhost:8081/uaa/oauth/token
            user-authorization-uri: http://localhost:8081/uaa/oauth/authorize
            #client-authentication-scheme: form
            scope: read, write
        resource:
            user-info-uri: http://localhost:8082/api/user
            #filter-order: 3
            jwt:
                # Tells the JWT framework to fetch the public key from the authorization server during startup
                # Note: The authorization server needs to be running...
                key-uri: http://localhost:8081/uaa/oauth/token_key
 
logging:
  level:
    org.springframework.security: DEBUG 