server:
    port: 8082
    contextPath: /api
#    session:
#      cookie:
#        name: RESOURCESESSION    
        
security:
    oauth2:
        resource:
            filter-order: 3
            jwt:
                # Tells the JWT framework to fetch the public key from the authorization server during startup
                # Note: The authorization server needs to be running...
                key-uri: http://localhost:8081/uaa/oauth/token_key
                
logging:
  level:
    org:
      springframework:
        security=DEBUG